# Generated by Django 5.1.3 on 2025-05-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HotelName', models.CharField(max_length=200, unique=True)),
                ('RoomAvilable', models.IntegerField(default=0)),
                ('Location', models.CharField(max_length=200)),
                ('Rating', models.FloatField(default=5, max_length=0)),
                ('PricePer', models.IntegerField(default=0)),
                ('Status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=200)),
                ('UserID', models.IntegerField(unique=True)),
                ('BookingCost', models.IntegerField(default=0)),
                ('BookingRoom', models.CharField(max_length=200)),
                ('Status', models.BooleanField(default=True)),
            ],
        ),
    ]
